
modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Iunius118/ToLaserBlade/issues"

[[mods]]
modId="tolaserblade"
version="${file.jarVersion}"
displayName="ToLaserBlade"
updateJSONURL="https://raw.githubusercontent.com/Iunius118/ToLaserBlade/master/update.json"
displayURL="https://github.com/Iunius118/ToLaserBlade"
logoFile="tolaserblade_logo.png"
credits="Created by Iunius118.  Translation by kazmurenko (ru_ru), tankyap (zh_cn), XuyuEre (zh_cn)."
authors="Iunius118"
description="Adds a Laser Blade."

[[dependencies.tolaserblade]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tolaserblade]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
