
modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Iunius118/ToLaserBlade/issues"

[[mods]]
modId="tolaserblade"
version="${file.jarVersion}"
displayName="ToLaserBlade"
updateJSONURL="https://raw.githubusercontent.com/Iunius118/ToLaserBlade/main/update.json"
displayURL="https://github.com/Iunius118/ToLaserBlade"
logoFile="tolaserblade_logo.png"
credits="Created by Iunius118.  Translation by kazmurenko (ru_ru), tankyap (zh_cn), XuyuEre (zh_cn)."
authors="Iunius118"
description="Adds a Laser Blade."

[[dependencies.tolaserblade]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tolaserblade]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
