# Workflows require read and write permissions in the repository

name: release_draft
on:
  push:
    tags:
      - 'v*'

jobs:
  release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'   # When using Java 8, set 'temurin'
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6
      - name: cache
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: create release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: |
            common/build/libs/*.jar
            fabric/build/libs/*.jar
            forge/build/libs/*.jar
            neoforge/build/libs/*.jar
            datagen/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
